CIRC-1415: Log4j 2.17.1
Log4j 2.16.0 causes this error message many times when running mod-circulation.jar:

2022-01-12 18:28:05,983 main ERROR Unable to create Lookup for bundle java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/lookup/JndiLookup
        at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:81)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:631)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:243)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:289)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at org.folio.circulation.support.VertxAssistant.<init>(VertxAssistant.java:15)
        at org.folio.circulation.Launcher.main(Launcher.java:35)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.lookup.JndiLookup
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 14 more

Bumping log4j version from 2.16.0 to 2.17.1 avoids this error message and also avoids false positive vulnerability reports from security scanners about log4j 2.16.0.